#-----------------------------------------------------------------------------
#|                                                                           |
#| File Name:     NPSS_Tests.yml                                             |
#| Author(s):     Michael Stich                                              |
#| Date(s):       March 2023                                                 |
#|                                                                           |
#| Description:   YAML script that connects to the NPSS shell server and     |
#|                executes command arguments to test the proposed NPSS code  |
#|                                                                           |
#-----------------------------------------------------------------------------
name: NPSS Tests
on: [push,pull_request]
jobs:
  NPSS_Scan:
    name: NPSS Error/Warning Scan
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - run: >
          Clear-Content ..\..\..\..\currentOutput.txt;
          cmd /c "..\..\..\..\setup-npss.bat && runnpss-psl.bat 1>NUL 2>..\..\..\..\currentOutput.txt";

          $content = Get-Content ..\..\..\..\currentOutput.txt;
          if ($content) 
          {
            Write-Host "The NPSS Code Pushed Contains The Following Errors/Warnings:"; 
            Get-Content ..\..\..\..\currentOutput.txt;
            $dateTime = Get-Date; 
            $dateTimeString = $dateTime.ToString("yyyy-MM-dd_HH-mm-ss");
            New-Item -ItemType File -Path "..\..\..\..\outputLogs\$dateTimeString.txt" | Out-Null;
            Set-Content ..\..\..\..\outputLogs\$dateTimeString.txt $content;
            Clear-Content ..\..\..\..\currentOutput.txt;
            exit 1
          }

  NPSS_Tester:
    name: NPSS Unit Tester
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - run: >
          cmd /c "..\..\..\..\setup-npss.bat && testnpss.bat 1>NUL 2>..\..\..\..\currentOutput.txt";

          $content = Get-Content ..\..\..\..\currentOutput.txt;
          if ($content) 
          {
            Write-Host "The NPSS Code Pushed Contains The Following Unit Test Errors/Warnings:"; 
            Get-Content ..\..\..\..\currentOutput.txt;
            Clear-Content ..\..\..\..\currentOutput.txt;
            exit 1
          }