#-----------------------------------------------------------------------------
#|                                                                           |
#| File Name:     stats_check.yml                                            |
#| Author(s):     Michael Stich                                              |
#| Date(s):       March 2023                                                 |
#|                                                                           |
#| Description:   YAML script that checks if the YAML file being pushed was  |
#|                modified                                                   |
#|                                                                           |
#-----------------------------------------------------------------------------
name: Status Check

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.ref }}
        fetch-depth: 0

    - name: Compare .github Folders
      id: compare
      run: |
        git diff --quiet HEAD^ HEAD .github || exit 1

    - name: Set Pull Request Status
      if: always()
      uses: actions/github-script@v4
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const conclusion = ${{ job.status }};
          const pullRequest = context.payload.pull_request;
          const octokit = new github.GitHub(token);
          octokit.repos.createCommitStatus({
            owner: context.repo.owner,
            repo: context.repo.repo,
            sha: pullRequest.head.sha,
            state: conclusion,
            context: 'github-folder-check',
            description: conclusion === 'success' ? 'YAMl file not modified, good to merge!' : 'The ./github/workflows file was changed by ${GITHUB_ACTOR}. Aborting workflow because of the possibility of malicious intent.',
            target_url: 'https://example.com',
          });
