#-----------------------------------------------------------------------------
#|                                                                           |
#| File Name:     stats_check.yml                                            |
#| Author(s):     Michael Stich                                              |
#| Date(s):       March 2023                                                 |
#|                                                                           |
#| Description:   YAML script that checks if the YAML file being pushed was  |
#|                modified                                                   |
#|                                                                           |
#-----------------------------------------------------------------------------
name: Status Check
on: [pull_request]

jobs:
  YAMLCheck:
    name: Yaml Modification Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Check for YAML File Changes       
        run: |
          git diff HEAD^ HEAD
            # echo "::error::The ./github/workflows file was changed by ${GITHUB_ACTOR}. Aborting workflow because of the possibility of malicious intent."
