#-----------------------------------------------------------------------------
#|                                                                           |
#| File Name:     stats_checks.yml                                           |
#| Author(s):     Michael Stich                                              |
#| Date(s):       March 2023                                                 |
#|                                                                           |
#| Description:   YAML script that checks if the YAML file being pushed was  |
#|                modified                                                   |
#|                                                                           |
#-----------------------------------------------------------------------------
name: Status Check
on: push
jobs:
  YAMLCheck:
    name: Yaml Modification Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Check for YAML File Changes       
        run: |
          if git diff --quiet HEAD@{1} HEAD .github/workflows; then
          else
            echo "::error::The ./github/workflows file was changed by ${GITHUB_ACTOR}. Aborting workflow because of the possibility of malicious intent."
            exit 1
          fi