#-----------------------------------------------------------------------------
#|                                                                           |
#| File Name:     stats_check.yml                                            |
#| Author(s):     Michael Stich                                              |
#| Date(s):       March 2023                                                 |
#|                                                                           |
#| Description:   YAML script that checks if the YAML file being pushed was  |
#|                modified                                                   |
#|                                                                           |
#-----------------------------------------------------------------------------
name: Status Check

on: [push]
jobs:
  YAMLCheck:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.ref }}
        fetch-depth: 0

    - name: Compare .github Folders
      id: compare
      run: |
        diff=$(git diff --name-only HEAD^ HEAD .github)
        if [ -n "$diff" ]; then
          echo "::error::The ./github/** directory was changed by ${GITHUB_ACTOR}. Aborting workflow because of the possibility of malicious intent."
          exit 1
        else
          echo "No Files Were Modified in ./github/** Safe to Proceed With Runners"
          exit 0
        fi

  NPSS_Output:
    needs: YAMLCheck