/*******************************************************************************
© Copyright 2003. The U.S. Government, as Represented by the Administrator of
the National Aeronautics and Space Administration (NASA). All rights reserved.
Includes content licensed from the U.S. Government, National Aeronautics and
Space Administration under United States Copyright Registration Numbers
V3503D364 and V3482D344.
© 2008-2015 NPSS® Consortium, www.NPSSConsortium.org/AllRightsReserved
*******************************************************************************/

/*******************************************************************************
NPSS® software and related documentation is export controlled with an Export
Control Classification Number(ECCN) of 9D991, controlled for Anti-Terrorism
reasons, under U.S. Export Administration Regulations 15 CFR 730-774. It may
not be transferred to a country checked under anti-terrorism on the Commerce
Country Chart structure or to foreign nationals of those countries in the U.S.
or abroad without first obtaining a license from the Bureau of Industry and
Security, United States Department of Commerce. Violations are punishable by
fine, imprisonment, or both.
*******************************************************************************/

/*******************************************************************************
This example is intended to test the aero cable sizing code. It has 2 subsystems,
an AC one and a DC one. Both subsystems include a cable, with some voltage across
them. The input side of the cables see a constant voltage, and the output side
voltages are independents intended to be varied to achieve a constant power
through the cable and desired power factor as well. The system is run to design
the cables, and then run off design at the same point, as well as a point with
increased power to see how variables change
*******************************************************************************/


//include viewers
#include "npssel.view"
#include "npssel_runtime.view"

MODELNAME = "Cable Test";

// select model
#include "test_model/cable_test.mdl"
#include "test_utils/TestingUtils.fnc"
solver.maxIterations = 5000;
solver.maxJacobians = 1000;
solverSequence = { "ACS", "DCS", "ACCable", "DCCable" };
setOption("switchDes","DESIGN");
					
autoSolverSetup();

cout << "--- On Design ---" << endl;
cout << endl << "Solver Sequence:" << endl << solverSequence << endl;
cout << "Dependents:" << endl << solver.dependentNames << endl;
cout << "Independents:" << endl << solver.independentNames << endl;

// Initial guesses
// ACCable.Ireal = 1100;
// ACCable.Iimag = 0;
// DCCable.Ireal = 1100;
// DCCable.Iimag = 0;

cout << "CASE #" << CASE++ << endl;
run();
printOutput();

real errTol = 0.000001;

// ACCable Tests
real effCalc = ((ACCable.EP_I.S.r - ACCable.EP_I.I.mag**2* ACCable.Z.mag)/ ACCable.EP_I.S.r);
testParameterDifference("ACCable","Efficiency",errTol,ACCable.eff,effCalc);

real measCalc = (ACCable.EP_I.VLN.r - (ACCable.EP_O.VLN.r));
testParameterDifference("ACCable","dV_meas",errTol,ACCable.dV.r,measCalc);

real realCurrentDifference = (ACCable.EP_I.I.r - ACCable.EP_O.I.r);
real imagCurrentDifference = (ACCable.EP_I.I.j - ACCable.EP_O.I.j);
testCurrentDifference("ACCable",errTol,realCurrentDifference,imagCurrentDifference);

// DCCable Tests
effCalc = ((DCCable.EP_I.S.r - DCCable.EP_I.I.mag**2* DCCable.Z.mag)/ DCCable.EP_I.S.r);
testParameterDifference("DCCable","Efficiency",errTol,DCCable.eff,effCalc);

measCalc = (DCCable.EP_I.VLN.r - (DCCable.EP_O.VLN.r));
testParameterDifference("DCCable","dV_meas",errTol,DCCable.dV.r,measCalc);

realCurrentDifference = (DCCable.EP_I.I.r - DCCable.EP_O.I.r);
imagCurrentDifference = (DCCable.EP_I.I.j - DCCable.EP_O.I.j);
testCurrentDifference("DCCable",errTol,realCurrentDifference,imagCurrentDifference);


cout << "--- Off Design ---" << endl;
setOption("switchDes","OFFDESIGN");
// For off design, stop varying the source.
ACS.ind_Iimag.autoSetup = FALSE;
ACS.dep_PF.autoSetup    = FALSE;
ACS.ind_Ireal.autoSetup = FALSE;
ACS.dep_Power.autoSetup = FALSE;
DCS.ind_Ireal.autoSetup = FALSE;
DCS.dep_Power.autoSetup = FALSE;
autoSolverSetup();
cout << solverSequence << endl;
cout << "Dependent and Independent Variables: (Please note in a successful test there should be no dependent or independent variables)" << endl;
cout << endl << solver.dependentNames << endl << solver.independentNames << endl;

// Run off-design, same inputs
cout << "CASE #" << CASE++ << endl;
run();
printOutput();


// ACCable Tests
effCalc = ((ACCable.EP_I.S.r - ACCable.EP_I.I.mag**2* ACCable.Z.mag)/ ACCable.EP_I.S.r);
testParameterDifference("ACCable","Efficiency",errTol,ACCable.eff,effCalc);

measCalc = (ACCable.EP_I.VLN.r - (ACCable.EP_O.VLN.r));
testParameterDifference("ACCable","dV_meas",errTol,ACCable.dV.r,measCalc);

realCurrentDifference = (ACCable.EP_I.I.r - ACCable.EP_O.I.r);
imagCurrentDifference = (ACCable.EP_I.I.j - ACCable.EP_O.I.j);
testCurrentDifference("ACCable",errTol,realCurrentDifference,imagCurrentDifference);

// DCCable Tests
effCalc = ((DCCable.EP_I.S.r - DCCable.EP_I.I.mag**2* DCCable.Z.mag)/ DCCable.EP_I.S.r);
testParameterDifference("DCCable","Efficiency",errTol,DCCable.eff,effCalc);

measCalc = (DCCable.EP_I.VLN.r - (DCCable.EP_O.VLN.r));
testParameterDifference("DCCable","dV_meas",errTol,DCCable.dV.r,measCalc);

realCurrentDifference = (DCCable.EP_I.I.r - DCCable.EP_O.I.r);
imagCurrentDifference = (DCCable.EP_I.I.j - DCCable.EP_O.I.j);
testCurrentDifference("DCCable",errTol,realCurrentDifference,imagCurrentDifference);



// Run off-design, increase power by increasing voltage drop (decrease voltage on output side of cable.
ACS.Ireal *= 0.9999;
ACS.Iimag /= 0.9;
DCS.Ireal *= 0.99945;
cout << "CASE #" << CASE++ << " -- increased power" << endl;
run();
printOutput();


// ACCable Tests
effCalc = ((ACCable.EP_I.S.r - ACCable.EP_I.I.mag**2* ACCable.Z.mag)/ ACCable.EP_I.S.r);
testParameterDifference("ACCable","Efficiency",errTol,ACCable.eff,effCalc);

measCalc = (ACCable.EP_I.VLN.r - (ACCable.EP_O.VLN.r));
testParameterDifference("ACCable","dV_meas",errTol,ACCable.dV.r,measCalc);

realCurrentDifference = (ACCable.EP_I.I.r - ACCable.EP_O.I.r);
imagCurrentDifference = (ACCable.EP_I.I.j - ACCable.EP_O.I.j);
testCurrentDifference("ACCable",errTol,realCurrentDifference,imagCurrentDifference);

// DCCable Tests
effCalc = ((DCCable.EP_I.S.r - DCCable.EP_I.I.mag**2* DCCable.Z.mag)/ DCCable.EP_I.S.r);
testParameterDifference("DCCable","Efficiency",errTol,DCCable.eff,effCalc);

measCalc = (DCCable.EP_I.VLN.r - (DCCable.EP_O.VLN.r));
testParameterDifference("DCCable","dV_meas",errTol,DCCable.dV.r,measCalc);

realCurrentDifference = (DCCable.EP_I.I.r - DCCable.EP_O.I.r);
imagCurrentDifference = (DCCable.EP_I.I.j - DCCable.EP_O.I.j);
testCurrentDifference("DCCable",errTol,realCurrentDifference,imagCurrentDifference);
